require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Max: 3

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Rails/FilePath:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf